version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gishow_postgres
    restart: always
    environment:
      POSTGRES_USER: gishow_user
      POSTGRES_PASSWORD: gishow_password
      POSTGRES_DB: gishow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: gishow_fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://gishow_user:gishow_password@db:5432/gishow_db
    depends_on:
      - db

volumes:
  postgres_data:
