import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ZoomIn,ZoomOut,Maximize,Layers,ArrowRight,Accessibility,DoorOpen,MousePointer2} from 'lucide-react';
import {Salon,Seat} from '../types';
import {formatPrice,toPersianDigits} from '../utils/formatters';
import {buildSeatLayout} from '../utils/seatLayout';
interface Props{salon:Salon;seats:Seat[];selected:string[];owned?:string[];disabled?:boolean;canSelect:boolean;preview?:boolean;onToggle:(id:string)=>void}
const tiers={vip:'جایگاه ویژه',ground:'همکف',balcony:'بالکن',lodge:'لژ'};
export function SeatPlanExplorer({salon,seats,selected,owned=[],disabled=false,canSelect,preview=false,onToggle}:Props){
 const [active,setActive]=useState<string|null>(null),[zoom,setZoom]=useState(1),[focused,setFocused]=useState(''),[hovered,setHovered]=useState<Seat|null>(null);
 const viewport=useRef<HTMLDivElement>(null);
 const part=salon.parts.find(p=>p.id===active);
 const sectionSeats=useMemo(()=>seats.filter(s=>s.partId===active).sort((a,b)=>a.row-b.row||a.number-b.number),[seats,active]);
 const layout=useMemo(()=>buildSeatLayout(sectionSeats,part?.shape,salon.aislesCount),[sectionSeats,part?.shape,salon.aislesCount]);
 useEffect(()=>{setFocused(sectionSeats[0]?.id||'');setHovered(null);setZoom(Math.min(1,(viewport.current?.clientWidth||700)/layout.width));},[active]);
 const status=(s:Seat)=>selected.includes(s.id)?'selected':owned.includes(s.id)?'owned':s.status==='sold'?'sold':s.status==='available'?'available':'reserved';
 const label={available:'آزاد',selected:'انتخاب شما',owned:'رزرو شما',sold:'فروخته‌شده',reserved:'غیرآزاد'};
 const toggle=(s:Seat)=>{if(canSelect&&!disabled&&s.status==='available'&&(selected.includes(s.id)||selected.length<10))onToggle(s.id);};
 function move(event:React.KeyboardEvent<SVGGElement>,seat:Seat){
  if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle(seat);return;}
  if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;
  event.preventDefault();const same=sectionSeats.filter(s=>s.row===seat.row);let next:Seat|undefined;
  if(event.key==='ArrowLeft'||event.key==='ArrowRight')next=same[same.findIndex(s=>s.id===seat.id)+(event.key==='ArrowRight'?1:-1)];
  else {const row=layout.rows[layout.rows.indexOf(seat.row)+(event.key==='ArrowDown'?1:-1)];next=sectionSeats.filter(s=>s.row===row).sort((a,b)=>Math.abs(a.number-seat.number)-Math.abs(b.number-seat.number))[0];}
  if(next){setFocused(next.id);event.currentTarget.ownerSVGElement?.querySelector<SVGGElement>(`[data-seat-id="${CSS.escape(next.id)}"]`)?.focus();}
 }
 const stage=<div className={`venue-stage venue-stage-${salon.stagePosition||'top'}`}><span>صحنه اجرا</span><small>{salon.stagePosition==='center'?'صحنه مرکزی':salon.stagePosition==='thrust'?'صحنه پیش‌آمده':'رو به تماشاگران'}</small></div>;
 return <section className="venue-explorer"><div className="venue-toolbar"><div><h3>{active?part?.name:'پلان سالن'}</h3><p>{active?'صندلی دلخواه را روی نقشه انتخاب کنید.':'برای دیدن صندلی‌ها، یک جایگاه را انتخاب کنید.'}</p></div>{active?<button className="site-secondary" onClick={()=>setActive(null)}><ArrowRight size={15}/>نمای کلی سالن</button>:<span className="venue-live"><i/>{preview?'موجودی نمونه':'موجودی همین سانس'}</span>}</div>
 <div className="venue-legend">{(['available','selected','reserved','sold'] as const).map(s=><span key={s}><i className={`seat-dot seat-${s}`}/>{label[s]}</span>)}{owned.length>0&&<span><i className="seat-dot seat-owned"/>رزرو شما</span>}</div>
 {!active?<div className="venue-overview"><div className="venue-guide"><Layers size={16}/>طرح شماتیک بر اساس جایگاه‌های ثبت‌شده؛ اندازه و فاصله بلوک‌ها مقیاس ساختمانی ندارند.</div>{!['bottom','center'].includes(salon.stagePosition||'top')&&stage}<div className={`venue-sections ${salon.stagePosition==='center'?'venue-sections-center':''}`}>{salon.stagePosition==='center'&&stage}{salon.parts.map(p=>{const list=seats.filter(s=>s.partId===p.id),free=list.filter(s=>s.status==='available').length,prices=list.map(s=>s.price);return <button key={p.id} className={`venue-section tier-${p.tier} shape-${p.shape||'straight'}`} onClick={()=>setActive(p.id)} aria-label={`مشاهده صندلی‌های ${p.name}`}><span className="venue-section-tier">{tiers[p.tier]}</span><strong>{p.name}</strong><div className="venue-mini-chairs" aria-hidden="true">{list.slice(0,32).map(s=><i key={s.id} className={`seat-${status(s)}`}/>)}</div><span className="venue-section-count">{toPersianDigits(free)} آزاد از {toPersianDigits(list.length)}</span><span className="venue-section-price">{prices.length?`از ${formatPrice(Math.min(...prices))}`:'بدون صندلی ثبت‌شده'}</span>{selected.some(id=>list.some(s=>s.id===id))&&<b className="venue-selected-badge">{toPersianDigits(selected.filter(id=>list.some(s=>s.id===id)).length)} انتخاب</b>}</button>;})}</div>{salon.stagePosition==='bottom'&&stage}<p className="venue-direction">جایگاه‌ها از تنظیمات سالن خوانده شده‌اند؛ شماره هر صندلی در نمای جزئیات نمایش داده می‌شود.</p></div>:<>
 <div className="venue-detail-heading"><div>{part?.isAccessible&&<span><Accessibility size={15}/>دسترسی ویژه</span>}{part?.doorAccess&&<span><DoorOpen size={15}/>{part.doorAccess}</span>}<span>{toPersianDigits(sectionSeats.filter(s=>s.status==='available').length)} صندلی آزاد</span></div><div className="venue-zoom"><button onClick={()=>setZoom(z=>Math.max(.25,z-.2))} aria-label="کوچک‌نمایی پلان"><ZoomOut size={18}/></button><span>{toPersianDigits(Math.round(zoom*100))}٪</span><button onClick={()=>setZoom(z=>Math.min(2.5,z+.2))} aria-label="بزرگ‌نمایی پلان"><ZoomIn size={18}/></button><button onClick={()=>setZoom(Math.min(1,(viewport.current?.clientWidth||700)/layout.width))} aria-label="جا دادن پلان در کادر"><Maximize size={17}/></button></div></div>
 <div ref={viewport} className="venue-map-viewport" tabIndex={0} aria-label="ناحیه نقشه صندلی‌ها؛ برای حرکت افقی از نوار پیمایش استفاده کنید" dir="ltr">
 <svg width={layout.width*zoom} height={layout.height*zoom} viewBox={`0 0 ${layout.width} ${layout.height}`} className="venue-seat-svg" role="group" aria-label={`صندلی‌های ${part?.name}`}>
 <path d={`M ${layout.width*.18} 26 Q ${layout.width/2} 4 ${layout.width*.82} 26`} fill="none" stroke="#f59e0b" strokeWidth="3"/><text x={layout.width/2} y="10" textAnchor="middle" className="venue-stage-label">سمت صحنه</text>
 {layout.rows.map((row,index)=><React.Fragment key={row}><text x="23" y={80+index*52} textAnchor="middle" className="venue-row-label">{toPersianDigits(row)}</text><text x={layout.width-23} y={80+index*52} textAnchor="middle" className="venue-row-label">{toPersianDigits(row)}</text></React.Fragment>)}
 {layout.positions.map(({seat:s,x,y,rotation})=>{const state=status(s),blocked=!canSelect||disabled||s.status!=='available'||(!selected.includes(s.id)&&selected.length>=10);return <g key={s.id} data-seat-id={s.id} role="button" tabIndex={focused===s.id?0:-1} aria-disabled={blocked} aria-pressed={selected.includes(s.id)} aria-label={`${s.partName}؛ ردیف ${toPersianDigits(s.row)}؛ صندلی ${toPersianDigits(s.number)}؛ ${formatPrice(s.price)}؛ ${label[state]}`} className={`venue-chair seat-${state}`} transform={`translate(${x} ${y}) rotate(${rotation} 16 18)`} onClick={()=>toggle(s)} onFocus={()=>{setFocused(s.id);setHovered(s);}} onMouseEnter={()=>setHovered(s)} onMouseLeave={()=>setHovered(null)} onKeyDown={e=>move(e,s)}><title>{`ردیف ${s.row}، صندلی ${s.number}؛ ${formatPrice(s.price)}؛ ${label[state]}`}</title><rect className="chair-focus" x="-5" y="-5" width="42" height="46" rx="10" fill="none"/><rect x="4" y="1" width="24" height="24" rx="7"/><rect x="1" y="15" width="5" height="19" rx="2"/><rect x="26" y="15" width="5" height="19" rx="2"/><rect x="6" y="25" width="20" height="10" rx="3"/><text x="16" y="18" textAnchor="middle">{toPersianDigits(s.number)}</text></g>;})}
 </svg></div><div className="venue-seat-hint" role="status">{hovered?<span>{hovered.partName}؛ ردیف {toPersianDigits(hovered.row)}، صندلی {toPersianDigits(hovered.number)} · {formatPrice(hovered.price)} · {label[status(hovered)]}</span>:<span><MousePointer2 size={14}/>شماره ردیف در دو طرف است؛ با کلیدهای جهت بین صندلی‌ها حرکت کنید.</span>}</div>{!sectionSeats.length&&<p className="site-notice">در این جایگاه صندلی ثبت نشده است.</p>}</>}
 </section>;
}

