import React,{useMemo,useRef,useState} from 'react';
import {X,Ticket,MapPin,Trash2} from 'lucide-react';
import {EventItem,RunTurn,Salon,Seat} from '../types';
import {SeatPlanExplorer} from './SeatPlanExplorer';
import {formatPrice,toPersianDigits} from '../utils/formatters';
import {useDialogFocus} from '../hooks/useDialogFocus';
interface Props{theme:'light'|'dark';event:EventItem;runTurn:RunTurn;salon:Salon;onClose:()=>void;onProceedToCheckout:(seats:Seat[])=>void;initialSelectedSeatIds?:string[]}
export const SeatMapModal:React.FC<Props>=({theme,event,runTurn,salon,onClose,onProceedToCheckout,initialSelectedSeatIds=[]})=>{
 const seats=useMemo(()=>salon.parts.flatMap(p=>Array.from({length:p.rows},(_,r)=>Array.from({length:p.seatsPerRow},(_,s)=>({id:`${p.id}-r${r+1}-s${s+1}`,partId:p.id,partName:p.name,row:(p.rowStart||1)+r,number:s+1,price:runTurn.tierPrices?.[p.tier]??p.price,status:((r*19+s*7)%13===0?'sold':(r*11+s*3)%17===0?'reserved':'available') as Seat['status']}))).flat()),[salon,runTurn]);
 const [selected,setSelected]=useState(initialSelectedSeatIds.filter(id=>seats.some(s=>s.id===id&&s.status==='available')));const ref=useRef<HTMLDivElement>(null);useDialogFocus(ref,onClose);
 const chosen=seats.filter(s=>selected.includes(s.id));
 return <div className="seat-booking-overlay" dir="rtl" data-site-theme={theme}><div ref={ref} role="dialog" aria-modal="true" aria-label="پیش‌نمایش پلان سالن" className="seat-booking-dialog site-surface"><header className="seat-booking-header"><div className="seat-booking-brand"><Ticket size={24}/><div><span>پیش‌نمایش انتخاب صندلی</span><h2>{event.title}</h2></div></div><button className="site-secondary" onClick={onClose} aria-label="بستن پلان نمونه"><X size={18}/></button></header><div className="seat-booking-info"><span><MapPin size={15}/>{salon.name}</span><span>{runTurn.date}، ساعت {runTurn.time}</span></div>
 <div className="seat-booking-layout"><div className="seat-booking-map"><p className="site-notice mb-4">این پلان برای بررسی طراحی است؛ موجودی و خرید آن نمونه هستند و رزرو واقعی ایجاد نمی‌کنند.</p><SeatPlanExplorer salon={salon} seats={seats} selected={selected} preview canSelect onToggle={id=>setSelected(ids=>ids.includes(id)?ids.filter(s=>s!==id):[...ids,id])}/></div><aside className="seat-booking-summary"><div className="seat-summary-title"><Ticket size={18}/><h3>انتخاب شما</h3><span>{toPersianDigits(chosen.length)}</span></div>{!chosen.length&&<p className="seat-summary-empty">یک جایگاه را باز کنید و صندلی دلخواه را انتخاب کنید.</p>}<div className="seat-summary-list">{chosen.map(s=><div className="seat-summary-item" key={s.id}><div><span>{s.partName}</span><strong>ردیف {toPersianDigits(s.row)} · صندلی {toPersianDigits(s.number)}</strong><small>{formatPrice(s.price)}</small></div><button onClick={()=>setSelected(ids=>ids.filter(id=>id!==s.id))} aria-label={`حذف صندلی ${s.number} ردیف ${s.row}`}><Trash2 size={15}/></button></div>)}</div><div className="seat-summary-total"><span>جمع مبلغ نمونه</span><strong>{formatPrice(chosen.reduce((n,s)=>n+s.price,0))}</strong></div><p className="site-muted text-xs">حداکثر ده صندلی قابل انتخاب است.</p><button className="site-primary w-full" disabled={!chosen.length} onClick={()=>onProceedToCheckout(chosen)}>ادامه پیش‌نمایش خرید</button></aside></div></div></div>;
};
