import React,{useState,useEffect} from 'react';
import {FloorPlan,LayoutRect,PartOfSalon} from '../types';
import {VenueFloorPlan} from './VenueFloorPlan';
interface Props {activePartId?:string;parts:PartOfSalon[];plan?:FloorPlan;onChange:(parts:PartOfSalon[],plan:FloorPlan|undefined)=>void;onSelectPart:(index:number)=>void}
export function VenueLayoutEditor({activePartId,parts,plan,onChange,onSelectPart}:Props){
 const [selected,setSelected]=useState('stage');
 useEffect(()=>{if(activePartId)setSelected(`part:${activePartId}`);},[activePartId]);
 function enable(){onChange(parts.map((p,i)=>({...p,placement:p.placement||{x:7+(i%2)*48,y:23+Math.floor(i/2)*Math.min(20,70/Math.ceil(parts.length/2)),width:38,height:Math.min(16,60/Math.ceil(parts.length/2))}})),{stage:{x:30,y:4,width:40,height:12},fixtures:[]});}
 const regions=plan?[{name:'صحنه اجرا',r:plan.stage},...parts.filter(p=>p.placement).map(p=>({name:p.name,r:p.placement!}))]:[];
 const overlaps=regions.flatMap((a,i)=>regions.slice(i+1).filter(b=>a.r.x<b.r.x+b.r.width&&a.r.x+a.r.width>b.r.x&&a.r.y<b.r.y+b.r.height&&a.r.y+a.r.height>b.r.y).map(b=>`${a.name} و ${b.name}`));
 const part=parts.find(p=>`part:${p.id}`===selected),fixture=plan?.fixtures.find(f=>f.id===selected),rect=selected==='stage'?plan?.stage:part?.placement||fixture;
 function update(value:LayoutRect){if(!plan)return;const r={...value,x:Math.max(0,Math.min(value.x,100-value.width)),y:Math.max(0,Math.min(value.y,100-value.height))};if(part)onChange(parts.map(p=>p.id===part.id?{...p,placement:r}:p),plan);else if(selected==='stage')onChange(parts,{...plan,stage:r});else onChange(parts,{...plan,fixtures:plan.fixtures.map(f=>f.id===selected?{...f,...r}:f)});}
 function select(id:string){setSelected(id);const idx=parts.findIndex(p=>`part:${p.id}`===id);if(idx>=0)onSelectPart(idx);}
 function add(kind:'door'|'aisle'){if(!plan||plan.fixtures.length>=30)return;const id=`fixture-${crypto.randomUUID()}`;onChange(parts,{...plan,fixtures:[...plan.fixtures,{id,kind,label:kind==='door'?'درب ورودی':'راهرو',x:2,y:25,width:kind==='door'?12:4,height:kind==='door'?6:50}]});setSelected(id);}
 return <section className="venue-layout-editor" dir="rtl"><div className="venue-toolbar"><div><h3>چیدمان اختصاصی سالن</h3><p>محل عناصر را با کشیدن، کلیدهای جهت یا مقدار عددی تنظیم کنید.</p></div></div>{!plan?<div className="site-notice"><p>برای این سالن هنوز مختصات جایگاه‌ها ثبت نشده است. با شروع ویرایش، چیدمان اولیه ساخته می‌شود و می‌توانید آن را مطابق نقشه سالن تنظیم کنید.</p><button type="button" className="site-primary" onClick={enable}>شروع تنظیم چیدمان</button></div>:<>
 <label className="text-xs">عنصر فعال<select className="site-input w-full mt-2" aria-label="عنصر فعال چیدمان" value={selected} onChange={e=>select(e.target.value)}><option value="stage">صحنه اجرا</option>{parts.map(p=><option key={p.id} value={`part:${p.id}`}>{p.name}</option>)}{plan.fixtures.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>
 <div className="floor-editor-actions"><button type="button" className="site-secondary" onClick={()=>add('aisle')} disabled={plan.fixtures.length>=30}>افزودن راهرو</button><button type="button" className="site-secondary" onClick={()=>add('door')} disabled={plan.fixtures.length>=30}>افزودن درب</button></div>
 <VenueFloorPlan parts={parts} plan={plan} active={selected} onSelect={select} onMove={(id,x,y)=>{const p=parts.find(p=>`part:${p.id}`===id),r=id==='stage'?plan.stage:p?.placement||plan.fixtures.find(f=>f.id===id);if(!r)return;const next={...r,x:Math.round(x*10)/10,y:Math.round(y*10)/10};if(p)onChange(parts.map(a=>a.id===p.id?{...a,placement:next}:a),plan);else if(id==='stage')onChange(parts,{...plan,stage:next});else onChange(parts,{...plan,fixtures:plan.fixtures.map(f=>f.id===id?{...f,...next}:f)});}}/>
 {rect&&<div className="floor-inspector"><strong>{part?.name||fixture?.label||'صحنه اجرا'}</strong>{fixture&&<label>نام عنصر<input className="site-input" value={fixture.label} maxLength={100} onChange={e=>onChange(parts,{...plan,fixtures:plan.fixtures.map(f=>f.id===selected?{...f,label:e.target.value}:f)})}/></label>}<div className="floor-coordinate-fields">{([['x','فاصله از چپ'],['y','فاصله از بالا'],['width','عرض'],['height','ارتفاع']] as const).map(([key,label])=><label key={key}>{label}، درصد<input className="site-input" type="number" dir="ltr" min={key==='width'||key==='height'?2:0} max={100} step="0.1" value={rect[key]} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))update({...rect,[key]:Math.max(key==='width'||key==='height'?2:0,Math.min(100,n))});}}/></label>)}</div>{fixture&&<button type="button" className="site-secondary" onClick={()=>{onChange(parts,{...plan,fixtures:plan.fixtures.filter(f=>f.id!==selected)});setSelected('stage');}}>حذف عنصر انتخاب‌شده</button>}</div>}
 {overlaps.length>0&&<p className="site-notice" role="status">بخشی از این عناصر روی هم قرار گرفته‌اند؛ محل آن‌ها را بررسی کنید: {overlaps.join('؛ ')}</p>}
 <p className="site-muted text-xs">مختصات نسبت به کادر سالن ذخیره می‌شوند. راهروهای این نقشه محل عبور بین جایگاه‌ها هستند؛ فاصله بین صندلی‌ها در تنظیمات هر جایگاه مشخص می‌شود. تغییرات پس از ذخیره سالن منتشر می‌شوند.</p>
 </>}</section>;
}
