import React from 'react';
import {FloorPlan,PartOfSalon} from '../types';
import {toPersianDigits} from '../utils/formatters';
interface Props {parts:PartOfSalon[];plan:FloorPlan;active?:string;onSelect:(id:string)=>void;onMove?:(id:string,x:number,y:number)=>void;counts?:Record<string,{free:number;total:number}>}
export function VenueFloorPlan({parts,plan,active,onSelect,onMove,counts}:Props){
 const drag=React.useRef<{id:string;x:number;y:number;startX:number;startY:number;w:number;h:number}|null>(null);
 const elements=[{id:'stage',label:'صحنه اجرا',kind:'stage',...plan.stage},...plan.fixtures,...parts.map(p=>({id:`part:${p.id}`,label:p.name,kind:'part',...p.placement!}))];
 return <svg className="floor-plan-svg" viewBox="0 0 1000 700" role="group" aria-label={onMove?'ویرایش محل عناصر سالن':'چیدمان ثبت‌شده سالن'} onPointerMove={e=>{const d=drag.current;if(!d||!onMove)return;const r=e.currentTarget.getBoundingClientRect();onMove(d.id,Math.max(0,Math.min(100-d.w,d.x+(e.clientX-d.startX)/r.width*100)),Math.max(0,Math.min(100-d.h,d.y+(e.clientY-d.startY)/r.height*100)));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <defs><pattern id="floor-grid" width="25" height="25" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="currentColor" opacity=".12"/></pattern></defs><rect width="1000" height="700" rx="18" fill="url(#floor-grid)"/>
 {elements.map(el=>{const part=el.kind==='part'?parts.find(p=>`part:${p.id}`===el.id):undefined,c=part&&counts?.[part.id];const interactive=!!onMove||!!part;return <g key={el.id} role={interactive?'button':undefined} tabIndex={interactive?0:undefined} aria-label={onMove?`ویرایش ${el.label}`:part?`مشاهده صندلی‌های ${el.label}`:undefined} aria-pressed={interactive?active===el.id:undefined} className={`floor-element floor-${el.kind} ${part?`tier-${part.tier}`:''} ${active===el.id?'is-active':''}`} transform={`translate(${el.x*10} ${el.y*7})`} onFocus={()=>interactive&&onSelect(el.id)} onClick={()=>interactive&&onSelect(el.id)} onPointerDown={e=>{if(!onMove)return;e.preventDefault();onSelect(el.id);e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:el.id,x:el.x,y:el.y,w:el.width,h:el.height,startX:e.clientX,startY:e.clientY};}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(el.id);}if(onMove&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?5:1;onMove(el.id,Math.max(0,Math.min(100-el.width,el.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0))),Math.max(0,Math.min(100-el.height,el.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0))));}}}>
 <rect width={el.width*10} height={el.height*7} rx={el.kind==='aisle'?3:12}/><text x={el.width*5} y={el.height*3.5-(part&&c?8:0)} textAnchor="middle" dominantBaseline="middle">{el.label}</text>{part&&c&&<text className="floor-count" x={el.width*5} y={el.height*3.5+16} textAnchor="middle">{toPersianDigits(c.free)} آزاد از {toPersianDigits(c.total)}</text>}
 </g>;})}
 </svg>;
}
