"""baseline"""
from alembic import op
import sqlalchemy as sa

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_bank_terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('terminal_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_bank_terminals_id'), 'tbl_bank_terminals', ['id'], unique=False)
    op.create_table('tbl_markdown_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('fixed_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_markdown_lists_code'), 'tbl_markdown_lists', ['code'], unique=True)
    op.create_index(op.f('ix_tbl_markdown_lists_id'), 'tbl_markdown_lists', ['id'], unique=False)
    op.create_table('tbl_salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_salons_id'), 'tbl_salons', ['id'], unique=False)
    op.create_table('tbl_user_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('national_code', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_lists_id'), 'tbl_user_lists', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_lists_mobile'), 'tbl_user_lists', ['mobile'], unique=True)
    op.create_table('tbl_barnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('sub_title', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('date_range', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cast_json', sa.Text(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('banner_gradient', sa.String(length=100), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['tbl_salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_barnames_id'), 'tbl_barnames', ['id'], unique=False)
    op.create_table('tbl_part_of_salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('seats_per_row', sa.Integer(), nullable=True),
    sa.Column('default_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['tbl_salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_part_of_salons_id'), 'tbl_part_of_salons', ['id'], unique=False)
    op.create_table('tbl_chairs_in_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['tbl_part_of_salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_chairs_in_part_id'), 'tbl_chairs_in_part', ['id'], unique=False)
    op.create_table('tbl_run_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barname_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('weekday', sa.String(length=50), nullable=False),
    sa.Column('is_sold_out', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['barname_id'], ['tbl_barnames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_run_turns_id'), 'tbl_run_turns', ['id'], unique=False)
    op.create_table('tbl_chair_in_barname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_turn_id', sa.Integer(), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chair_id'], ['tbl_chairs_in_part.id'], ),
    sa.ForeignKeyConstraint(['run_turn_id'], ['tbl_run_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_chair_in_barname_id'), 'tbl_chair_in_barname', ['id'], unique=False)
    op.create_table('tbl_factor_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_number', sa.String(length=50), nullable=False),
    sa.Column('tracking_code', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('run_turn_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_mobile', sa.String(length=20), nullable=False),
    sa.Column('customer_national_code', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('qr_payload', sa.String(length=500), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_turn_id'], ['tbl_run_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_factor_lists_factor_number'), 'tbl_factor_lists', ['factor_number'], unique=True)
    op.create_index(op.f('ix_tbl_factor_lists_id'), 'tbl_factor_lists', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_factor_lists_tracking_code'), 'tbl_factor_lists', ['tracking_code'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_factor_lists_tracking_code'), table_name='tbl_factor_lists')
    op.drop_index(op.f('ix_tbl_factor_lists_id'), table_name='tbl_factor_lists')
    op.drop_index(op.f('ix_tbl_factor_lists_factor_number'), table_name='tbl_factor_lists')
    op.drop_table('tbl_factor_lists')
    op.drop_index(op.f('ix_tbl_chair_in_barname_id'), table_name='tbl_chair_in_barname')
    op.drop_table('tbl_chair_in_barname')
    op.drop_index(op.f('ix_tbl_run_turns_id'), table_name='tbl_run_turns')
    op.drop_table('tbl_run_turns')
    op.drop_index(op.f('ix_tbl_chairs_in_part_id'), table_name='tbl_chairs_in_part')
    op.drop_table('tbl_chairs_in_part')
    op.drop_index(op.f('ix_tbl_part_of_salons_id'), table_name='tbl_part_of_salons')
    op.drop_table('tbl_part_of_salons')
    op.drop_index(op.f('ix_tbl_barnames_id'), table_name='tbl_barnames')
    op.drop_table('tbl_barnames')
    op.drop_index(op.f('ix_tbl_user_lists_mobile'), table_name='tbl_user_lists')
    op.drop_index(op.f('ix_tbl_user_lists_id'), table_name='tbl_user_lists')
    op.drop_table('tbl_user_lists')
    op.drop_index(op.f('ix_tbl_salons_id'), table_name='tbl_salons')
    op.drop_table('tbl_salons')
    op.drop_index(op.f('ix_tbl_markdown_lists_id'), table_name='tbl_markdown_lists')
    op.drop_index(op.f('ix_tbl_markdown_lists_code'), table_name='tbl_markdown_lists')
    op.drop_table('tbl_markdown_lists')
    op.drop_index(op.f('ix_tbl_bank_terminals_id'), table_name='tbl_bank_terminals')
    op.drop_table('tbl_bank_terminals')
    # ### end Alembic commands ###
