"""accounts"""
from alembic import op
import sqlalchemy as sa

revision = '0002_accounts'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('auth_throttles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('auth_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['tbl_user_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_auth_recovery_codes_user_id'), 'auth_recovery_codes', ['user_id'], unique=False)
    op.create_table('auth_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['auth_permissions.code'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_code')
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user_lists.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('auth_user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=80), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['auth_permissions.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user_lists.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_code')
    )
    op.create_table('auth_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user_lists.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('auth_event_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['tbl_barnames.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user_lists.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id', 'role_id')
    )
    op.add_column('tbl_user_lists', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###

    permissions = sa.table('auth_permissions', sa.column('code', sa.String), sa.column('name', sa.String), sa.column('scope', sa.String))
    definitions = [
        ('accounts.manage', 'مدیریت حساب‌ها و تخصیص دسترسی', 'global'),
        ('roles.manage', 'مدیریت نقش‌ها و مجوزها', 'global'),
        ('terminals.read', 'مشاهده پایانه‌ها', 'global'),
        ('salons.manage', 'مدیریت سالن‌ها', 'global'),
        ('events.read', 'مشاهده برنامه‌های مدیریتی', 'event'),
        ('reports.read', 'مشاهده فروش برنامه', 'event'),
        ('seats.manage', 'مسدودسازی صندلی برنامه', 'event'),
        ('tickets.check', 'کنترل ورود برنامه', 'event'),
    ]
    op.bulk_insert(permissions, [dict(code=c, name=n, scope=s) for c, n, s in definitions])
    roles = sa.table('auth_roles', sa.column('id', sa.Integer), sa.column('code', sa.String), sa.column('name', sa.String), sa.column('scope', sa.String))
    op.bulk_insert(roles, [dict(id=1, code='admin', name='مدیر سامانه', scope='global'),
                          dict(id=2, code='customer', name='خریدار', scope='global'),
                          dict(id=3, code='producer', name='برگزارکننده', scope='event'),
                          dict(id=4, code='checker', name='متصدی ورود', scope='event')])
    grants = sa.table('auth_role_permissions', sa.column('role_id', sa.Integer), sa.column('permission_code', sa.String))
    op.bulk_insert(grants, [dict(role_id=1, permission_code=c) for c, n, s in definitions] +
                          [dict(role_id=3, permission_code=c) for c in ('events.read', 'reports.read', 'seats.manage')] +
                          [dict(role_id=4, permission_code=c) for c in ('events.read', 'tickets.check')])
    # Legacy single-role strings are intentionally not promoted to authorization.
    op.execute(sa.text("INSERT INTO auth_user_roles (user_id, role_id) SELECT id, 2 FROM tbl_user_lists"))
    if op.get_bind().dialect.name == 'postgresql':
        op.execute(sa.text("SELECT setval(pg_get_serial_sequence('auth_roles', 'id'), 4)"))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user_lists', 'is_active')
    op.drop_table('auth_event_roles')
    op.drop_table('auth_user_roles')
    op.drop_table('auth_user_permissions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('auth_role_permissions')
    op.drop_index(op.f('ix_auth_recovery_codes_user_id'), table_name='auth_recovery_codes')
    op.drop_table('auth_recovery_codes')
    op.drop_table('auth_audit')
    op.drop_table('auth_throttles')
    op.drop_table('auth_roles')
    op.drop_table('auth_permissions')
    # ### end Alembic commands ###
